Update Examples page: LTFU Workflow
medic/cht-docs pull request #1094
Opened 2023-05-26 00:06 UTC by Phil-Mwago

2023-05-26 02:43 UTC, mrjones-plip commented
Hey @Phil-Mwago !  We use "assign" field for who is doing the work on the ticket.  We use "Reviewers" for who is reviewing the ticket.

you have assigned me the ticket - would you like me to work on it with you?

2023-05-26 07:03 UTC, Phil-Mwago commented
> 

@mrjones-plip yes, we can work together on this. Kindly review.

2023-05-29 11:48 UTC, esthermmoturi requested changes
@mrjones-plip and @Phil-Mwago do you think we should get rid of the problem to be solved and solution overview subheadings?

2023-05-29 11:48 UTC, esthermmoturi commented on content/en/apps/examples/interoperability.md
> +This workflow describes a use case where a health facility/requesting system generates a list of patients who have missed appointments for follow-up through on the CHT. A Community Health Worker (CHW
```suggestion
This workflow describes a use case where a health facility or a requesting system generates a list of patients who have missed follow-up appointments that were made through the CHT. A CHW would then follow up with the listed patients through SMS, a physical visit or a phone call.
```

2023-05-29 11:48 UTC, esthermmoturi commented on content/en/apps/examples/interoperability.md
> +Data exchange between the CHT and other systems has primarily been at peer-to-peer level. This means that the integration is built to meet the specific need in the unique scenarios. This presents a p
```suggestion
Data exchange between the CHT and other systems has primarily been at peer-to-peer level. In most cases, integration is built to meet the specific needs on case-by-case basis. This limits maintenance and scalability as there are no defined standards that are used. Interoperability allows technical teams to scale in an efficient and repeatable manner due to the predefined standards. 

```

2023-05-29 11:48 UTC, esthermmoturi commented on content/en/apps/examples/interoperability.md
> +The intended users of the interoperable systems are Community Health Workers (CHWs) on the CHT side and Healthcare Givers on the requesting system side. System administrators can access the mediator
```suggestion
The intended users of the interoperable systems are CHWs on the CHT side and Healthcare Givers on the requesting system side. System administrators can access the mediator on the administration console. 

```

2023-05-29 11:48 UTC, esthermmoturi commented on content/en/apps/examples/interoperability.md
> +Data exchange between the CHT and other systems has primarily been at peer-to-peer level. This means that the integration is built to meet the specific need in the unique scenarios. This presents a p
```suggestion
Data exchange between the CHT and other systems has primarily been at peer-to-peer level. This means that the integration is built to meet the specific need in the unique scenarios. This presents a problem during maintainance and scalability as there are no defined standards that have been used. [Interoperability](https://docs.communityhealthtoolkit.org/apps/concepts/interoperability/) allows technical teams to scale in an efficient and repeatable manner due to the already predefined standards. 

```

2023-05-30 18:15 UTC, mrjones-plip commented
Yeah - I like the feature parity and think we should keep "problem to be solved" and "solution overview"!

2023-05-31 07:33 UTC, merged