Refining user bulk load documentation
medic/cht-docs pull request #1115
Opened 2023-06-12 10:26 UTC by esthermmoturi

2023-09-14 22:38 UTC, garethbowen commented
@esthermmoturi Is this ready for review?

2023-09-18 07:43 UTC, esthermmoturi commented
@garethbowen I am working to get it ready by end of this week.

2023-09-27 03:07 UTC, esthermmoturi commented
@mrjones-plip , any luck reviewing this pull request?

2023-09-27 19:14 UTC, mrjones-plip commented
Hey @esthermmoturi !  Sorry for the delay in getting back to. Also - thanks for taking some time to improve our bulk user upload docs!

I'm going to use this PR to improve your process of updating the CHT docs.  I suspect it will ttake longer, but hopefully be helpful in the long run.  

Every PR should have a goal. Often that's in the form of a ticket. For example, see "[fully offline CHT deployment](https://github.com/medic/cht-docs/issues/441)". If it's just a PR (that's fine!), we need to put the goals in the PR.  Goals helps for two reasons:
* The reviewer knows what to look for, what  to compliment on, what to give constructive criticism on
* The author can review their work to make sure it's achieving the goals they stated


My request is for you to follow these guidelines and review your own changes in this PR.:

1. Write a goal or three in [the body](https://github.com/medic/cht-docs/pull/1115#issue-1752422394) of the PR.  Maybe something like, "This PR adds more explicit steps on matching the user upload gsheet template to the actual deployed app config" or maybe "This PR removes confusion around ambiguous terms of 'update' vs 'upload' vs 'create'" (these are both hypothetical!"
2. Consider that if your change is just an opinion with out adding any facts or details, don't make the change.  So if the original text was "This is how to write an input form for the CHT" and you change it to "After reading this document, you'll know how to write an input form for the CHT" - just keep the original text, you're not adding anything new.
3. If you remove content, have a reason.  For example, if we have "nginx uses memcachd to store often used static binary files often referenced by HTTPS2 requests" - that's probably too detailed! We could safely say , "Our web server, nginx, has caching to improve performance when serving images over HTTP2"
4. In general, try to write as concisely as possible.   If the same thing can be said in fewer words, go for it! Have a good reason (per above) to make something longer when making a change.

To make it this more actionable, here's some examples in your PR where you can improve based on the guidelines above:

1. Write a goal:
   * "Refine" is to vauge
2. change is just an opinion:
   * I'm not sure the [sub-title change is better](https://github.com/medic/cht-docs/pull/1115/files#diff-2c65ce5c4cf3f1c29f81cc482a9bd73bb97b4b7eaaeb4f976b8295d0ef6ffb6eR6), it feels like an opinion
   * I think you're trying to [standardize on "Import" vs "Upload" ](https://github.com/medic/cht-docs/pull/1115/files#diff-2c65ce5c4cf3f1c29f81cc482a9bd73bb97b4b7eaaeb4f976b8295d0ef6ffb6eR19)- not an opinion, an improvement! Be sure you do it through out the doc
3. remove content, have a reason
    * I think it's important to [keep the explicit path](https://github.com/medic/cht-docs/pull/1115/files#diff-2c65ce5c4cf3f1c29f81cc482a9bd73bb97b4b7eaaeb4f976b8295d0ef6ffb6eL35) of the API and that it's a `POST`.  
    *  linking to "this" is always ambiguous and we should link to explicit terms so folks know what they're getting, like this [W3C post on the topic](https://www.w3.org/QA/Tips/noClickHere). this was removed in the above edit
    * I think the [page info box at the top](https://github.com/medic/cht-docs/pull/1115/files#diff-2c65ce5c4cf3f1c29f81cc482a9bd73bb97b4b7eaaeb4f976b8295d0ef6ffb6eL25) is important as it calls out facts readers shouldn't miss
4. write as concisely
   * I think [these two lines](https://github.com/medic/cht-docs/pull/1115/files#diff-2c65ce5c4cf3f1c29f81cc482a9bd73bb97b4b7eaaeb4f976b8295d0ef6ffb6eR47), could be condensed to:
   >  Before using bulk user upload , please familiarize yourself with the 3 sections of the spreadsheet:

2023-09-28 18:21 UTC, esthermmoturi commented
@mrjones-plip ,Thank you for the recommendation ,I will work on the issues you have raised.

2023-10-06 10:23 UTC, esthermmoturi commented
Hey @mrjones-plip , while I agree with some of the pointers indicated above, a couple of items have caught my attention:

1. I am standardizing the general framework of documentation and although the page info is a good way to summarize what is on the page, it adds no value and the outcome of the documentation is already highlighted in the first few lines of the documentation.If necessary, a summary of the feature can be placed under page description and will appear [here](https://docs.communityhealthtoolkit.org/apps/guides/data/).

> I think the [page info box at the top](https://github.com/medic/cht-docs/pull/1115/files#diff-2c65ce5c4cf3f1c29f81cc482a9bd73bb97b4b7eaaeb4f976b8295d0ef6ffb6eL25) is important as it calls out facts readers shouldn't miss

2. Our primary readers are semi and non-technical and to them wording makes a huge difference

> Consider that if your change is just an opinion with out adding any facts or details, don't make the change. So if the original text was "This is how to write an input form for the CHT" and you change it to "After reading this document, you'll know how to write an input form for the CHT" - just keep the original text, you're not adding anything new.

3. As I work on documentation changes, I follow the available documentation step by step and that is how I notice gaps. For example, for this documentation, explanations were scattered and a lot of things were assumed as evidenced from continuous contribution to [this](https://forum.communityhealthtoolkit.org/t/bulk-user-upload-chws-and-supervisors/2161) forum post.
 Unless a feature is extremely customizable or has many moving parts, documentation should guide a user from beginning to end without them having to ask for guidance.

4. I agree with adding goals on the PR. This is a fantastic suggestion
5.  I agree and will work on some of the removed content

> 
I think it's important to [keep the explicit path](https://github.com/medic/cht-docs/pull/1115/files#diff-2c65ce5c4cf3f1c29f81cc482a9bd73bb97b4b7eaaeb4f976b8295d0ef6ffb6eL35) of the API and that it's a POST.
linking to "this" is always ambiguous and we should link to explicit terms so folks know what they're getting, like this [W3C post on the topic](https://www.w3.org/QA/Tips/noClickHere). this was removed in the above edit

2023-10-06 15:41 UTC, mrjones-plip commented
@esthermmoturi  - wow - you rock! Thanks so much for digging into my feedback in earnest.  I can see you put a lot of thought and effort into this.  I really appreciate your time.

Once you've made some your changes to the PR, I'll give it another review.

Otherwise, diving into some of your response below. 

----
>>  I think the [page info box at the top](https://github.com/medic/cht-docs/pull/1115/files#diff-2c65ce5c4cf3f1c29f81cc482a9bd73bb97b4b7eaaeb4f976b8295d0ef6ffb6eL25) is important as it calls out facts readers shouldn't miss
>
> I am standardizing the general framework of documentation and although the page info is a good way to summarize what is on the page, it adds no value and the outcome of the documentation is already highlighted in the first few lines of the documentation.If necessary, a summary of the feature can be placed under page description and will appear [here](https://docs.communityhealthtoolkit.org/apps/guides/data/).

I'm not sure I agree with this standardization to remove this page info box.  On many other pages we use this a way to call out which CHT version is needed to use the feature or what the primary use case is for the doc page. If a reader misses these, they could be trying to implement the wrong solution on a version of the CHT that doesn't support the feature:

![image](https://github.com/medic/cht-docs/assets/8253488/bc40a9d5-3758-4804-8d5c-1619684ca38f)

Maybe we can greatly simplify the one on this page?  If we keep some of the text you moved out , but still call out the version and google doc requirements - does that work?

![image](https://github.com/medic/cht-docs/assets/8253488/48909c8e-5237-4190-b905-9da29a81f2e4)

>>   Consider that if your change is just an opinion with out adding any facts or details, don't make the change. So if the original text was "This is how to write an input form for the CHT" and you change it to "After reading this document, you'll know how to write an input for
>
> Our primary readers are semi and non-technical and to them wording makes a huge difference

Gotcha!  Re-reading your changes, I can see where you're going with this.  Also noting you're fixing a number of typos as well!

> As I work on documentation changes, I follow the available documentation step by step and that is how I notice gaps. For example, for [this](https://forum.communityhealthtoolkit.org/t/bulk-user-upload-chws-and-supervisors/2161) documentation, explanations were scattered and a lot of things were assumed as evidenced from continuous contribution to this forum post.
>
> Unless a feature is extremely customizable or has many moving parts, documentation should guide a user from beginning to end without them having to ask for guidance.

Makes sense - I think redoing something step by step is one of, if not the, best way to confirm docs make sense. Thanks for your effort!

> I agree with adding goals on the PR. This is a fantastic suggestion
> 
>  I agree and will work on some of the removed content

yay!  thanks again for being receptive to feedback.

2023-11-27 05:48 UTC, esthermmoturi commented
@mrjones-plip , I have made a couple of changes following your suggestions and from my experience importing users. Where can I get as list of what each field means? I had a hard time differentiating between `contact.type`, `contact.contact_type` , `place.type` , `place.contact_type` and `type`. Are there any redundant fields that are not mapped(For creating user accounts, their contacts and places)?

2023-12-01 22:42 UTC, mrjones-plip commented
@esthermmoturi - tl;dr - those fields are used if they're present in the spreadsheet.  They represent the different names in the hierarchy for specific types of contacts.  

@m5r - do you have some time next week - can you do a pass at defining what each of these fields is used for?

2023-12-07 22:50 UTC, m5r commented
@esthermmoturi I dug into the cht code base and this is what I've found concerning the 5 fields you mentioned:

| field | description |
|-------|-------------|
| `{contact,place}.type`                | when creating a user, this is always supposed to be `contact`, other possible values are `district_hospital`, `health_center`, `clinic`, and `person` |
| `{contact,place}.contact_type` | this is specific to the deployment's configuration, it should be one of the contact types defined in the config's `contact_types` field |
| `type`                                            | this field is deprecated, use `roles` instead |

I grouped up `contact` and `place` because they're built the same way, the essentially have the same properties. Let me know if you have any other questions

cc @mrjones-plip

2024-01-11 12:08 UTC, esthermmoturi commented
Thanks @m5r , the descriptions were helpful. I have added the descriptions. @m5r and @mrjones-plip Could you kindly review this PR for anything that I might need to add/omit? Thank you for the assistance so far.

2024-01-17 06:09 UTC, mrjones-plip requested changes
We're getting closer!  Requesting some changes to tighten things up, fix a mistake or two.

2024-01-17 21:37 UTC, m5r commented on content/en/apps/guides/data/users-bulk-load.md
>      </ol>
I don't remember what was the intention behind this list's format. In the current state it's an ordered list with letters `a.` `b.` `c.` and markdown can't do that natively, hence the use of HTML here.  
I don't feel strongly either way

2024-01-17 21:41 UTC, m5r approved these changes
Nothing to add to Ashley's review, fantastic work Mariachana :+1:

2024-01-17 21:57 UTC, mrjones-plip commented on content/en/apps/guides/data/users-bulk-load.md
>      </ol>
ah -  I totally missed that this is an `<ol/>` and not a `<ul/>` - good catch @m5r! Knowing that, this seems benign enough to be an  `<ul/>` and use the native markup.

2024-01-17 22:19 UTC, m5r commented on content/en/apps/guides/data/users-bulk-load.md
>      </ol>
Yes, totally, go for it!

2024-01-18 12:35 UTC, esthermmoturi commented on content/en/apps/guides/data/users-bulk-load.md
> +Contact spreadsheets are named according to the user role, for example when creating users who are chws and others who are chw_supervisors, the following contact spreadsheets are populated respective
Thanks for the semi colon  use suggestion, I'll look through it.

2024-01-18 18:41 UTC, esthermmoturi commented on content/en/apps/guides/data/users-bulk-load.md
>      </ol>
@mrjones-plip , so should we change this?

2024-01-18 18:42 UTC, esthermmoturi commented on content/en/apps/guides/data/users-bulk-load.md
> +11. `contact.type` or `place.type`: this column when creating a user, is logged as contact, other possible values are district_hospital, health_center, clinic, and person
@mrjones-plip , is it just me who can't see the next suggestion?

2024-01-18 18:43 UTC, mrjones-plip commented on content/en/apps/guides/data/users-bulk-load.md
>      </ol>
yups!

2024-01-18 18:43 UTC, mrjones-plip commented on content/en/apps/guides/data/users-bulk-load.md
> +11. `contact.type` or `place.type`: this column when creating a user, is logged as contact, other possible values are district_hospital, health_center, clinic, and person
sorry - it's [this one](https://github.com/medic/cht-docs/pull/1115#discussion_r1454656454)

2024-01-18 19:39 UTC, esthermmoturi commented on content/en/apps/guides/data/users-bulk-load.md
> +11. `contact.type` or `place.type`: this column when creating a user, is logged as contact, other possible values are district_hospital, health_center, clinic, and person
Thanks, I see it.

2024-01-18 20:11 UTC, esthermmoturi commented on content/en/apps/guides/data/users-bulk-load.md
>      <ol type="a">
```suggestion
    <ul >
```

2024-01-18 20:15 UTC, esthermmoturi commented on content/en/apps/guides/data/users-bulk-load.md
>      <ol type="a">
```suggestion
    <ul>
```

2024-01-18 20:16 UTC, esthermmoturi commented on content/en/apps/guides/data/users-bulk-load.md
>      </ol>
```suggestion
    </ul>
```

2024-01-18 20:18 UTC, esthermmoturi commented on content/en/apps/guides/data/users-bulk-load.md
>      </ol>
Done in latest commits

2024-01-19 21:02 UTC, mrjones-plip approved these changes
Thanks for working through all these improvements @esthermmoturi !   These are good to go.

One minor fix, if you want, is [to make this list](https://github.com/medic/cht-docs/pull/1115#discussion_r1454647532) markdown instead of HTML.   I wasn't suggesting we move the from `<ol>` -> `<ul>` but that they be markdown.  No biggie - change if you want - but it's good to go as is!

2024-01-22 06:24 UTC, merged