chore: new permission clarification
medic/cht-docs pull request #1150
Opened 2023-08-11 07:34 UTC by latin-panda

2023-08-11 07:43 UTC, latin-panda commented
Hi @esthermmoturi, I want to add a note on performance implications when enabling default filters in the Reports tab. 
Online users with many reports, such as 10k, 20k, 50k etc, can experience bad performance whenever 1 or more filters are applied that match thousands of reports.

2023-08-14 08:42 UTC, esthermmoturi requested changes

2023-08-14 08:42 UTC, esthermmoturi commented on content/en/apps/reference/app-settings/user-permissions.md
> +| `can_default_facility_filter` | Defaults the Place Filter in Reports tab to the user's associated facility. The user should have a contact associated that belongs to a facility. This feature is not
```suggestion
| `can_default_facility_filter` | Defaults the Place Filter in Reports tab to the user's associated facility. The user should have a contact associated that belongs to a facility. This feature is not available for Admin and Offline type of users. Use with caution, online users that can access thousands of reports can experience slow performance especially where the network is slow. Added in 4.3.  |
```

2023-08-14 08:46 UTC, latin-panda commented on content/en/apps/reference/app-settings/user-permissions.md
> +| `can_default_facility_filter` | Defaults the Place Filter in Reports tab to the user's associated facility. The user should have a contact associated that belongs to a facility. This feature is not
Fixed! Thank you!

2023-08-14 09:34 UTC, esthermmoturi approved these changes

2023-08-14 12:41 UTC, merged