K3s VMware Setup
medic/cht-docs pull request #1192
Opened 2023-09-28 12:48 UTC by Hareet

k3s cluster setup on a VMware datacenter that uses VMware out-of-tree Cloud Provider Interface and Container Storage Interface. 

This enables the cluster to auto-provision storage volume mounts using CSI that talks to VMware API. Allows k3s to orchestrate pvc with ability to failover to a spare node if `drain node` is invoked.

2023-10-02 22:20 UTC, mrjones-plip requested changes
Wow WOW!   What an epic amount of work - congrats!!!

I went ahead and moved the file up a directory and renamed it to match our existing docs.  As well, I'm only reviewing this for document structure, slightly reducing the wall of text feeling and parity on code snippets all using same nomenclature ("password" vs password vs "`PASSWORD`" vs credentials etc). I'm not at all reviewing this for technical accuracy in deploying k3s!

finally, it's impossible (as far as I know) to do code blocks inside code blocks for suggestions, so I fell back to triple (`   `) or sextuple (`      `) spaces which achieves the same thing in the final markdown - whew!

2023-10-02 22:20 UTC, mrjones-plip commented on content/en/apps/guides/hosting/4.x/self-hosting-k3s-multinode.md
> +Procedure:
```suggestion
Follow the [VMware documentation for CSI](https://docs.vmware.com/en/VMware-vSphere-Container-Storage-Plug-in/2.0/vmware-vsphere-csp-getting-started/GUID-A1982536-F741-4614-A6F2-ADEE21AA4588.html) with these steps:
```

2023-10-02 22:20 UTC, mrjones-plip commented on content/en/apps/guides/hosting/4.x/self-hosting-k3s-multinode.md
> +
```suggestion
3) Create kubernetes secret, which will map authentication credentials and datacenter name to CSI containers. First, create a file  `/etc/kubernetes/csi-vsphere.conf`. Be sure to replace  `<vCenter_IP>`, `<USERNAME>`, `<PASSWORD>` ,  `<true_or_false>`,  `<PORT>` ,  `<datacenter1-path>` and  `<datacenter1-path>`  with your values:

   
   [Global]
   cluster-id = "<cluster-id>"
   
   [VirtualCenter "<vCenter_IP>"]
   insecure-flag = "<true_or_false>"
   user = "<USERNAME>"
   password = "<PASSWORD>"
   port = "<PORT>"
   datacenters = "<datacenter1-path>, <datacenter2-path>, ..."


```

2023-10-02 22:20 UTC, mrjones-plip commented on content/en/apps/guides/hosting/4.x/self-hosting-k3s-multinode.md
> +Please add "true" as the value for this key, seen below:
```suggestion
Please add `true` as the value for this key, seen below:
```

2023-10-02 22:20 UTC, mrjones-plip commented on content/en/apps/guides/hosting/4.x/self-hosting-k3s-multinode.md
> +We'll need to create a global [StorageClass](https://kubernetes.io/docs/concepts/storage/storage-classes/) resource in our k3s cluster, so cht-core deployments will be able to ask for persistent stor
```suggestion
We'll need to create a global [StorageClass](https://kubernetes.io/docs/concepts/storage/storage-classes/) resource in our k3s cluster, so CHT Core deployments will be able to ask for persistent storage volumes from the k3s cluster.
```

2023-10-02 22:20 UTC, mrjones-plip commented on content/en/apps/guides/hosting/4.x/self-hosting-k3s-multinode.md
> +* Note the storageClassName parameter should be identical to the storageClass we deployed earlier
```suggestion
Your persistent volume (PVC) template for all CouchDB's should be as shown below. Note the `storageClassName` parameter should be identical to the `storageClass` we deployed earlier:
```

2023-10-02 22:20 UTC, mrjones-plip commented on content/en/apps/guides/hosting/4.x/self-hosting-k3s-multinode.md
> +Another doc to be linked here
We can add this content when we have it, until then, we'll just remove the place holder.

```suggestion
```

2023-10-17 17:50 UTC, Hareet commented on content/en/apps/guides/hosting/4.x/self-hosting-k3s-multinode.md
> +A container orchestrater has the ability to schedule projects on available resources spread across a datacenter. For national scale projects, or a large number of cht-core deployments to maintain, we
yup, [kube-scheduler](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-scheduler/). I think you've defined it 👍

2023-10-17 18:03 UTC, Hareet commented on content/en/apps/guides/hosting/4.x/self-hosting-k3s-multinode.md
> +```
@mrjones-plip I wasn't sure about this edit. The same formatting is applied for all the varying curl commands (a few lines above and below the optional paramter changes here).

2023-10-17 19:32 UTC, nydr reviewed
Great job summarizing the process! Even though there's some things that are guaranteed to become outdated such as version numbers I think it's a very useful reference to have.

---
@mrjones-plip already came with great feedback on the texts so I don't have much to add, mostly minor comments 

1. Path should be changed to `content/en/apps/guides/hosting/4.x/self-hosting/<...>` due to rename in #1191 

2. Should this page be specific to VMware? If so I'd prefer to rename the url (filename) to include VMware and break out `Kubernetes Concepts` into a separate page.

3. If it'll be generic down the line I'd prefer to preemptively see any VMware specific steps under [`tabpane`](https://www.docsy.dev/docs/adding-content/shortcodes/#tabbed-panes) tabs like [here](https://docs.communityhealthtoolkit.org/apps/tutorials/local-setup/#installing-docker)

2023-10-17 19:32 UTC, nydr commented on content/en/apps/guides/hosting/4.x/self-hosting-k3s-multinode.md
> +wget https://raw.githubusercontent.com/kubernetes/cloud-provider-vsphere/release-1.25/releases/v1.25/vsphere-cloud-controller-manager.yaml
IMHO to realistically complete this process the reader is expected to understand standard *nix file management. Might be worth adding technical prerequisites at the top, but I don't have strong opinions regarding this.

2023-10-17 19:32 UTC, nydr commented on content/en/apps/guides/hosting/4.x/self-hosting-k3s-multinode.md
> +       <datacenter-name>/vm/<vm-name1> \
The tags disappears for me in the preview, does it look correctly in when rendered by the static site generator?

Minor: I'd prefer to wrap all code lines in backticks (replace `shell` with the language that is most appropriate or leave blank)
````
```shell
code goes here...
```
````
 or for shorter sections
`` `code goes here...` ``

2023-10-17 19:37 UTC, nydr commented
> to do code blocks inside code blocks for suggestions

@mrjones-plip you can use more backticks
`````
````
```
hello
```
````
`````

will render as

````
```
hello
```
````

2023-10-17 20:38 UTC, mrjones-plip commented
> @mrjones-plip Not sure if it works for suggestions but in comments you can use more backticks

OMG!!! YOU'RE MY SAVIOR.

Jokes aside, this is legit helpful. I looked and looked for an answer - I just needed to ask you!

2023-10-22 21:17 UTC, mrjones-plip approved these changes
Nice work @Hareet ! It ended up being easier to fix some of the code formatting and indentations myself, which I did in  f5a1d4e .

Otherwise, good to go!

2023-11-17 07:15 UTC, Reagan approved these changes

2023-11-17 09:52 UTC, esthermmoturi approved these changes

2023-11-28 02:13 UTC, merged