fix: Update link to be ignored by the link checker
medic/cht-docs pull request #1224
Opened 2023-11-01 07:53 UTC by andrablaj

# Description

Updates Google Drive link to be ignored by the link checker. [Discussion in Slack](https://medic.slack.com/archives/CUXB9SVT5/p1698789015037749?thread_ts=1698057359.974949&cid=CUXB9SVT5).

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

2023-11-01 13:30 UTC, mrjones-plip commented on .github/scripts/muffet.sh
> +  --exclude "https://drive.google.com/file/d/1YPXoba9gVmD7SP-X88PpJIsIVGvY86_G*" \
I believe `muffet` expects a regex, so we need a `.` here:

```suggestion
  --exclude "https://drive.google.com/file/d/1YPXoba9gVmD7SP-X88PpJIsIVGvY86_G.*" \
```

2023-11-01 13:30 UTC, mrjones-plip requested changes
we're one char away from an approve!

2023-11-01 20:13 UTC, andrablaj commented
Oh I went faster than the music @mrjones-plip! Thanks!

2023-11-02 00:10 UTC, mrjones-plip approved these changes
LGTM!

2023-11-02 07:03 UTC, merged