chore: update steps for local dev setup
medic/cht-docs pull request #1274
Opened 2024-01-22 10:01 UTC by latin-panda

# Description

Updates the steps for local dev setup

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

2024-01-22 12:14 UTC, Benmuiruri requested changes

2024-01-22 12:14 UTC, Benmuiruri commented on content/en/contribute/code/core/dev-environment.md
> +Confirm you have these four files in the `local-build` folder: `cht-core.yml`, `cht-couchdb.yml` and `cht-couchdb-clustered.yml`
Confirm you have these three files in the `local-build` folder: `cht-core.yml`, `cht-couchdb.yml` and `cht-couchdb-clustered.yml`

2024-01-22 12:16 UTC, Benmuiruri requested changes
Thanks for testing out and improving the docs. Just one small fix

2024-01-22 12:36 UTC, latin-panda commented on content/en/contribute/code/core/dev-environment.md
> +Confirm you have these four files in the `local-build` folder: `cht-core.yml`, `cht-couchdb.yml` and `cht-couchdb-clustered.yml`
Thanks!

2024-01-24 14:33 UTC, latin-panda commented
@Benmuiruri can you please review?

2024-01-24 16:53 UTC, Benmuiruri approved these changes

2024-01-25 02:18 UTC, merged