feat: Document looking up users from their `facility_id` or `contact_id`
medic/cht-docs pull request #1318
Opened 2024-03-21 16:32 UTC by m5r

# Description

Issue: medic/cht-core#8877
Code PR: medic/cht-core#8928

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

2024-03-22 04:46 UTC, sugat009 approved these changes

2024-03-22 21:01 UTC, jkuester requested changes
Looks good! Just hoping to get a bit more to match the other query parameter sections

2024-04-01 13:21 UTC, m5r commented on content/en/apps/reference/api.md
> +Get users with a specific `facility_id`:
Oooh yeah that's much better!

2024-04-02 21:18 UTC, jkuester approved these changes
LGTM!

2024-04-18 22:47 UTC, merged