chore(na): update hosting requirements and considerations per feedback
medic/cht-docs pull request #1440
Opened 2024-06-25 23:10 UTC by mrjones-plip

# Description

update hosting requirements and considerations per feedback

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

2024-06-25 23:11 UTC, mrjones-plip commented
cc @esthermmoturi

2024-06-26 05:01 UTC, garethbowen requested changes
Thanks for running with this! Suggestions inline.

2024-06-26 05:01 UTC, garethbowen commented on content/en/hosting/_index.md
> +* **Updates** - By definition TLS certificates expire and software needs to be updated - how will the deployment get these updates on a regular basis? CHT Core updates happen many times through out t
For me, TLS renewals are separate from Updates. What about this?

```suggestion
* **Updates** - CHT Core updates happen many times throughout the year - do you have a maintenance schedule for these and staff who are trained to do the upgrade?
* **Renewals** - Services such as TLS certificates and domains name registration expire periodically and will make the server inaccessible - do you have a schedule for monitoring and renewing these in a timely manner?
```

2024-06-26 17:30 UTC, mrjones-plip commented on content/en/hosting/_index.md
> +* **Backups** - What happens to the CHT data if there's a hard drive failure? Are there provisions for a [3-2-1 backup strategy](https://en.wikipedia.org/wiki/Backup#Storage)?
good thinking! fixed in d57c6553

2024-06-26 17:31 UTC, mrjones-plip commented
@garethbowen -  if there's no more changes requested, please merge so we can get these changes live as I'll be away from keyboard for a bit!

I'll otherwise tend to further improvements upon my return.

2024-06-27 06:10 UTC, garethbowen approved these changes
Definite improvement, thanks!

2024-06-27 06:11 UTC, merged