Fix copy and add dark mode
medic/cht-docs pull request #1535
Opened 2024-09-10 14:02 UTC by esthermmoturi

Things that have been implemented include:

- Style css files have been removed to ensure it is easier to keep up with changes and upgrades provided by hugo and docsy
- Dark mode was enabled for the CHT doc-site. This includes Auto, Dark and Light mode which can be changed from an icon close to the search box

Changes you might observe include:
- Colour changes for page-info, notes and other short-codes to accommodate dark mode.
-  The footer does not contain "All Rights Reserved" - this will be fixed if it is a necessity.
- All images are now placed below/before code snippets or text. This fixes [this issue](https://github.com/medic/cht-docs/issues/1475).

2024-09-10 14:04 UTC, esthermmoturi commented
Hey @jkuester , please let me know if you notice anything out of the ordinary with this change.

2024-09-10 20:26 UTC, jkuester requested changes
Dark mode AND -20,000 lines of CSS!  :heart_eyes: 

## Dark-mode

![image](https://github.com/user-attachments/assets/4349ebd0-a907-4b97-80d4-c248cd1183b7)

The embedded search results are not dark.  Maybe there is  a way to control this in our [gcse settings](https://www.docsy.dev/docs/adding-content/search/#setting-up-site-search)... :thinking: 

![image](https://github.com/user-attachments/assets/ab1771f3-3124-4718-a5a3-30394af23f2b)

The code blocks are not dark.  Maybe we need to tweak the [chroma settings](https://www.docsy.dev/docs/adding-content/lookandfeel/#lightdark-color-themes)?

## Colors

I figure even if we switch to a dark theme, we still will want some custom colors (which is something with first-class support [in docsy](https://www.docsy.dev/docs/adding-content/lookandfeel/#site-colors). 

## Formatting

### Sidebar

Previously we had some custom CSS around the sidebar that was trimming up the indentation and padding so it was more efficient with its use of space.  IMHO the sidebar is one area that we might be okay keeping our customizations.  Even if future updates to Docsy break our sidebar layout, it should be easy to detect (since you see the same sidebar on every page) and simple(ish) to resolve (since our customizations are limited to some SCSS code in one file...). Ultimately, I am fine sticking with the default sidebar just for the sake of simplicity, but did want to mention that customizing it should be feasible too...

### Images

The image layout situation is much more tricky.  On one hand, it definitely simplifies things to just inline the images without being able to float them next to each other or to the text.  However, I do think it makes the docs quite a bit more clunky to read. :disappointed: It is a bit confusing to me that the image floating ever worked with us just putting the bootstrap classes in with the `figure` shortcode. Not really surprised that  that we are getting stuff like https://github.com/medic/cht-docs/issues/1475 now.  

I am not a web dev expert, but IMHO if we want do more complex layouts than just inlineing the images with basic markdown formatting, we should just commit to doing it with explicit bootstrap containers.  Docsy uses bootstrap and it seems like this has to be how things have been working in the past for the floating images.  Going forwards perhaps we need to be more explicit about the layout by specifying containers/rows/columns.  (Could write our own shortcodes to make this easier, or maybe look into [this Hugo Module](https://bootstrap.hugomods.com/docs/).)

2024-09-11 07:05 UTC, esthermmoturi commented
Thank you @jkuester for the feedback.I'll add a checklist below for things that should be fixed.

- [ ] Fix code highlighting colour in dark mode
- [ ] Add sidebar customization

2024-09-11 07:27 UTC, esthermmoturi commented
By adding the ` _variables_project.scss` file, I have retained the padding and colour customization of the sidebar. The only customization I have removed was for the increased height of the header navbar since the light/dark menu was misplaced. This also has undone the image repositioning thus issue https://github.com/medic/cht-docs/issues/1475 remains open.

2024-09-12 15:04 UTC, jkuester approved these changes
:heart_eyes:  Looks great!  Just one minor suggestion to get the code syntax colors back.

> I think we can leave the search results as they are, do you think I should open a separate issue to fix it?

Agreed. Probably not a huge deal to fix this right now.  (My guess is that we will eventually have to target this with some custom CSS... :sweat: )  But, yeah, lets go ahead and log an issue for it just to track the fact that we know of the issue.

2024-09-12 15:04 UTC, jkuester commented on assets/scss/_variables_project.scss
> +      // color: #222222;
```suggestion
```

2024-09-12 18:23 UTC, esthermmoturi commented on assets/scss/_variables_project.scss
Thanks for being thorough and adding suggestions. I'll definitely reach out for any CSS queries or PRs

2024-09-12 18:25 UTC, merged