Fix bad links
medic/cht-docs pull request #1546
Opened 2024-09-18 08:00 UTC by esthermmoturi

# Description

Fixes bad links highlighted by  bot ran on Sep 15th 2024.

```
Run ./.github/scripts/muffet.sh
http://localhost:1313/hosting/4.x/app-developer/
	404	http://localhost:1313/apps/tutorials/local-setup/privacy.error.png
http://localhost:1313/building/guides/debugging/secure-sharing-of-developer-instance/
	404	http://localhost:1313/apps/guides/debugging/images/SSH.tunnel.diagram.svg
	404	http://localhost:1313/apps/guides/debugging/images/ssh.ports.svg
http://localhost:1313/contribute/code/
	502	https://alpha.dev.medicmobile.org/
http://localhost:1313/contribute/medic/onboarding/technical-resources/
	403	https://www.udacity.com/course/asynchronous-javascript-requests--ud109
http://localhost:1313/building/guides/data/analytics/couch2pg-to-cht-sync-migration/
	404	http://localhost:1313/building/guides/data/analytics/couch2pg-to-cht-sync-migration/(/building/guides/data/analytics/building-dbt-models/)
	404	http://localhost:1313/building/guides/data/analytics/couch2pg-to-cht-sync-migration/(/building/guides/data/analytics/production/)
	404	http://localhost:1313/building/guides/data/analytics/couch2pg-to-cht-sync-migration/(/building/guides/data/analytics/setup/)
	404	http://localhost:1313/building/guides/data/analytics/couch2pg-to-cht-sync-migration/(/hosting/monitoring/setup/)
http://localhost:1313/hosting/3.x/app-developer/
	404	http://localhost:1313/apps/tutorials/local-setup/privacy.error.png
Error: Process completed with exit code 1.
```

2024-09-18 13:46 UTC, mrjones-plip commented
@esthermmoturi - we should always use text instead of screenshots in tickets - this allows us to search for the content of the error messages.

thanks!

2024-09-18 15:15 UTC, esthermmoturi commented
Hey @mrjones-plip , not sure the image you are referring to, is it what I have placed in the description? If yes, it's a text block.

2024-09-18 19:33 UTC, mrjones-plip commented
Correct! It is a text block now, but was an image until I edited it ;)

![image](https://github.com/user-attachments/assets/ca45f832-1673-45f9-b52b-e0b40cc282da)

2024-09-19 06:01 UTC, esthermmoturi commented
My bad @mrjones-plip! Thanks. I will use text moving forward.

2024-09-19 14:27 UTC, andrablaj reviewed
@esthermmoturi I fixed the cht-sync doc related links last week in [this PR](https://github.com/medic/cht-docs/pull/1529/files), in addition to the removal of CHT Pipeline mentions and they have somehow been overwritten. Any chance to apply the changes in my PR to this PR too?

2024-09-19 15:02 UTC, esthermmoturi commented
Hey @andrablaj , please confirm that it's now okay.

2024-09-19 15:25 UTC, andrablaj commented
The problem seems to be in [this commit](https://github.com/medic/cht-docs/pull/1537/files#diff-1c4421545ac5dd7120937c0446d2af68c0f4c94b497cfa8953a3b67c18462fc9) where the changes I pushed (probably just before you messaged the team not to merge anything that day 😬) got overwritten. I can open a new PR if it makes is easier.

2024-09-19 15:44 UTC, esthermmoturi commented
@andrablaj Let me try merging with your branch. Give me a minute.

2024-09-19 15:56 UTC, andrablaj requested changes
For some reason a paragraph got duplicated. Otherwise all good!

2024-09-19 15:56 UTC, andrablaj commented on content/en/building/guides/data/analytics/couch2pg-to-cht-sync-migration.md
> +1. **Set up monitoring and alerting**: [Setup CHT Watchdog]({{< relref "hosting/monitoring/setup" >}}) to monitor the running of CHT Sync and CHT Pipeline and set up alerts for any failures.
```suggestion
```

2024-09-19 15:56 UTC, andrablaj commented on content/en/building/guides/data/analytics/couch2pg-to-cht-sync-migration.md
> +1. **Optimize**: Once the dbt models are working as expected and the dashboards display the expected data, optimize the models to improve performance. This may involve restructuring the models, addin
```suggestion
```

2024-09-19 17:02 UTC, andrablaj approved these changes
Looks good, thanks!

2024-09-20 06:43 UTC, merged