chore: add test data generator tool documentation
medic/cht-docs pull request #1583
Opened 2024-10-02 12:06 UTC by latin-panda

# Description

The Test Data Generator has been around for 1 year and more teams are using it. Adding it here will make it easier to discover for others. 

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

2024-10-02 12:07 UTC, latin-panda commented
Hi @esthermmoturi, Can you please review it? I'm not sure if this is the best place for this tool documentation

2024-10-02 16:13 UTC, esthermmoturi commented
Hey @latin-panda , I have reviewed and added a suggestion. We can leave the file where it's placed for now, I will move it later.

2024-10-02 16:15 UTC, esthermmoturi requested changes

2024-10-02 16:15 UTC, esthermmoturi commented on content/en/core/overview/test-data-generator.md
> +  This tool is intended for application builders or CHT developer contributors that have knowledge on the design of docs from the CHT's CouchDB. Design the test data that fits your project hierarchy
```suggestion
  A tool for CHT developers to design, generate, and push CouchDB docs tailored to project hierarchies and reports .
```

2024-10-02 16:15 UTC, esthermmoturi commented on content/en/core/overview/test-data-generator.md
> +This tool is intended for application builders or CHT developer contributors that have knowledge about the design of docs from the CHT's CouchDB.
```suggestion
```

2024-10-02 16:15 UTC, esthermmoturi commented on content/en/core/overview/test-data-generator.md
> +Design the test data that fit your project hierarchy and reports. The tool will generate CouchDB docs and push them into your CHT test instance.
```suggestion
Design the test data that fits your project hierarchy and reports. The tool will generate CouchDB docs and push them into your CHT test instance.
```

2024-10-03 09:38 UTC, esthermmoturi approved these changes
Thanks @latin-panda , approved!

2024-10-03 09:55 UTC, merged