Moving simple task file
medic/cht-docs pull request #1647
Opened 2024-10-23 12:35 UTC by esthermmoturi

Moving the [simple tasks](https://docs.communityhealthtoolkit.org/building/tutorials/tasks-1/) file to work on [this](https://github.com/medic/cht-docs/issues/1637).

This is what is expected.
<img width="279" alt="image" src="https://github.com/user-attachments/assets/9c1f09dd-bffd-4353-9d73-803a649ecbc0">

2024-10-23 12:40 UTC, andrablaj commented
@esthermmoturi, quick clarification before I review. The plan is to move everything from `Features` and `Tutorials` to `Building`?

2024-10-23 12:49 UTC, esthermmoturi commented
> @esthermmoturi, quick clarification before I review. The plan is to move everything from `Features` and `Tutorials` to `Building`?

Yes, that is the plan and to combine scattered concepts. I will also move items from `Concepts`

2024-10-23 13:00 UTC, andrablaj requested changes
Images load correctly and links are OK. Just a small comment about wording and a duplicated line.

In general, when building the subtitles of a section, I suggest avoiding the title name in each subtitle. For example, instead of "Building a task", "Configuring a task", etc., we could use "Building", "Configuring" to keep it simple.

2024-10-24 06:44 UTC, esthermmoturi commented on content/en/building/tasks/simple-tasks.md
> +linkTitle: Simple Tasks
I think we can leave this, we have [another file ](https://docs.communityhealthtoolkit.org/building/tutorials/tasks-2/)that I'll be moving on Complex Tasks. What do you think?

2024-10-24 08:58 UTC, andrablaj commented on content/en/building/tasks/simple-tasks.md
> +linkTitle: Simple Tasks
Oooh right, if there is a `Complex Tasks` page, it makes sense to keep it the way you added it. Thank you for the clarification!

2024-10-24 08:59 UTC, andrablaj approved these changes
💯

2024-10-24 10:00 UTC, merged