feat(#129): add openmrs and ltfu docs
medic/cht-docs pull request #1657
Opened 2024-10-28 09:41 UTC by witash

# Description

[description]

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

2024-11-12 08:05 UTC, njuguna-n commented on content/en/building/guides/interoperability/openhim.md
> +The structure of documents in the CHT database reflect the configuration of the system, and therefore do not map directly to a FHIR message format. To achieve interoperability we used a middleware to
```suggestion
The structure of documents in the CHT database reflect the configuration of the system, and therefore do not map directly to a FHIR message format. To achieve interoperability Medic used a middleware to convert the CHT data structure into a standardized form so the other systems can read it. Below is the standard data workflow:
```

https://docs.communityhealthtoolkit.org/contribute/docs/style-guide/#using-we

2024-11-12 08:12 UTC, njuguna-n commented on content/en/building/guides/interoperability/openhim.md
> +- `Postman` or similar tool for API testing. This will play the role of the `Requesting System` from the sequence diagram above.
The diagram linked on line 28 is not the form submission sequence diagram. Do we need the second sentence?

2024-11-12 08:13 UTC, njuguna-n commented on content/en/building/guides/interoperability/openmrs.md
> +   Exchange data with systems based on the OpenMRS using FHIR APIs
```suggestion
   Exchange data with systems based on OpenMRS using FHIR APIs
```

2024-11-12 08:17 UTC, njuguna-n commented on content/en/building/guides/interoperability/openmrs.md
> +Depending on what data needs to be exchanged, outbound push configurations and JSON forms need to be added to CHT.
Link to outbound push documentation here.

2024-11-12 08:18 UTC, njuguna-n commented on content/en/building/guides/interoperability/openmrs.md
> +After setting up the putbound push, test that it works in the test environment by creating a patient in the CHT application.
```suggestion
After setting up the outbound push config, test that it works in the test environment by creating a patient in the CHT application.
```

2024-11-12 18:03 UTC, lorerod requested changes
Thanks @witash. Left some suggestions inline. Let me know what you think.

2024-11-12 18:03 UTC, lorerod commented on content/en/building/guides/interoperability/openmrs.md
A similar [workflow](https://github.com/medic/cht-interoperability/blob/main/WORKFLOW.md) testing doc is an excellent complement to this documentation. And the corresponding [Postman collection for local testing](https://github.com/medic/cht-interoperability/tree/main/docs/local-test)

2024-11-28 09:16 UTC, andrablaj commented
@witash I merged the `main` branch into this branch to get the latest updates from the site revamp. This helps better understand the overall Building section structure.

2024-11-28 09:54 UTC, andrablaj requested changes
Thank you for the extended work in putting together this doc!
I shared a first batch of suggestions. Mainly:

- Replace `_` with `-` in the file/folder names.
- Simplify `linkTitle` names to make the hierarchy simpler to read and navigate.
- Added `weight` to pages so that the guides appear in a logical order. 

I will go through the OpenMRS steps and add more comments, if any.

2024-11-28 09:54 UTC, andrablaj commented on content/en/building/concepts/interoperability.md
> +  building/guides/interoperability/cht_config
```suggestion
  building/guides/interoperability/cht-config
```

2024-11-28 09:54 UTC, andrablaj commented on content/en/building/concepts/interoperability.md
> +  building/guides/interoperability/ltfu_reference_workflow
```suggestion
  building/guides/interoperability/ltfu
```

2024-11-28 09:54 UTC, andrablaj commented on content/en/building/guides/interoperability/cht_config.md
>  ---
Please replace `_` with `-` in the file name to ensure consistency across the repo.

2024-11-28 09:54 UTC, andrablaj commented on content/en/building/guides/interoperability/openhim.md
> +The structure of documents in the CHT database reflect the configuration of the system, and therefore do not map directly to a FHIR message format. To achieve interoperability Medic used a middleware
```suggestion
The structure of documents in the CHT database reflects the configuration of the system, and therefore, does not map directly to a FHIR message format. To achieve interoperability, the CHT uses a middleware to convert the CHT data structure into a standardized form so the other systems can read it. Below is the standard data workflow:
```

2024-11-28 09:54 UTC, andrablaj commented on content/en/building/guides/interoperability/openhim.md
> +This project uses OpenHIM as the middleware component with [Mediators](http://openhim.org/docs/configuration/mediators/) to do the conversion. [Outbound Push](https://docs.communityhealthtoolkit.org/
```suggestion
CHT Interoperability uses OpenHIM as the middleware component with [Mediators](http://openhim.org/docs/configuration/mediators/) to do the conversion. [Outbound Push](https://docs.communityhealthtoolkit.org/apps/reference/app-settings/outbound/) is configured to make a request to the middleware when relevant documents are created or modified in the CHT. A Mediator then creates a FHIR resource, which is then routed to OpenHIM. OpenHIM routes the resource to any other configured systems.
```

2024-11-28 09:54 UTC, andrablaj commented on content/en/building/guides/interoperability/openhim.md
> +See more information on the [CHT interoperability](https://docs.communityhealthtoolkit.org/apps/concepts/interoperability/) page on the CHT documentation site.
```suggestion
See more information on the [CHT interoperability page](https://docs.communityhealthtoolkit.org/apps/concepts/interoperability/).
```

2024-11-28 09:54 UTC, andrablaj commented on content/en/building/guides/interoperability/openhim.md
> +<img src="good-client-screen.png" width="600">
I don't get the same roles (`admin` is missing from what I see). I updated the screenshot in [this PR](https://github.com/medic/cht-interoperability/pull/153).

2024-11-28 09:54 UTC, andrablaj commented on content/en/building/guides/interoperability/openmrs.md
> +linkTitle: "OpenMRS Interoperability"
```suggestion
linkTitle: "OpenMRS"
```

2024-11-28 09:54 UTC, andrablaj commented on content/en/building/guides/interoperability/openmrs.md
> +  building/guides/interoperability/cht_config
```suggestion
  building/guides/interoperability/cht-config
```

2024-11-28 09:54 UTC, andrablaj commented on content/en/building/guides/interoperability/openmrs.md
> +Integrating CHT apps with OpenMRS can be achieved using the CHT's [Interoperability Tools]({{< ref "building/guides/interoperability/openhim" >}}) and following the guidance in the [Building interope
```suggestion
Integrating CHT apps with OpenMRS can be achieved using the CHT's [Interoperability Tools]({{< ref "building/guides/interoperability/openhim" >}}) and following the guidance in the [Building interoperability with FHIR APIs documentation]({{< ref "building/guides/interoperability/cht-config" >}}). 
```

2024-12-13 11:10 UTC, witash commented on content/en/building/guides/interoperability/openmrs.md
> +1. Set up a test environment including an OpenMRS instance, a CHT instance, and OpenHIM. The [interoperability project](https://github.com/medic/cht-interoperability) has docker compose files so that
changed to `up-openmrs`

2024-12-13 11:13 UTC, witash commented on content/en/building/guides/interoperability/openmrs.md
> +1. Create or find concepts in OpenMRS that represent any data that needs to be exchanged.
linked to OpenMRS documentation

2024-12-13 11:13 UTC, witash commented on content/en/building/guides/interoperability/openmrs.md
> +1. Set OpenMRS credentials and CHT credentials in the interoperability project, and start it in a production deployment.
linked to openhim setup section

2024-12-16 08:36 UTC, andrablaj commented
@witash I see various updates on this PR. Is it ready for another review?

2025-01-09 10:11 UTC, witash commented on content/en/building/guides/interoperability/openmrs.md
> +4. The mediator will attempt to find CHT locations by using a place id formatted like `[12345]` at the end of the address string. `place_id` must match a CHT place id. If `place_id` is not included i
removed all references to incoming patients

2025-01-09 10:15 UTC, witash commented on content/en/building/guides/interoperability/openmrs.md
> +After setting up the forms, test that it works in the test environment by creating a patient in OpenMRS.
In the OpenMRS Utils postman collection there is OpenMRS Create Patient, but for this doc, removed all references to incoming patients

2025-01-09 10:15 UTC, witash commented on content/en/building/guides/interoperability/openmrs.md
> +If all the above look OK, you should now be able to see the patient in CHT.
removed all references to incoming patients

2025-01-09 10:17 UTC, witash commented on content/en/building/guides/interoperability/openmrs.md
> +A default implementation is provided which uses the [OpenMRS address add on](https://addons.openmrs.org/show/org.openmrs.module.addresshierarchy) to match locations in OpenMRS to contacts in CHT.
Its not included in the openmrs docker compose that comes with cht-interoperability. 
removed all references to incoming patients

2025-01-10 08:40 UTC, witash commented on content/en/building/guides/interoperability/openmrs.md
> +The steps to create an OpenMRS interoperability workflow are:
do you have any specific suggestions?

2025-01-10 08:52 UTC, witash commented
> @witash I see various updates on this PR. Is it ready for another review?

I think this is ready for another review

2025-01-10 17:20 UTC, andrablaj commented on content/en/building/guides/interoperability/ltfu.md
> +An API test collection that can be used with Postman or similar tools can be found under `/docs/local-test`. This collection allows testing the LTFU flow while running the instances locally.
```suggestion
An API test collection that can be used with Postman or similar tools can be found under `/docs/local-test` in the [cht-interoperability repository](https://github.com/medic/cht-interoperability/tree/main/docs/local-test). This collection allows testing the LTFU flow while running the instances locally.
```

2025-01-10 17:22 UTC, andrablaj commented on content/en/building/guides/interoperability/openhim.md
> +#### Overview
```suggestion
### Overview
```

2025-01-10 17:23 UTC, andrablaj commented on content/en/building/guides/interoperability/openhim.md
> +#### CHT
```suggestion
#### Interoperability with the CHT
```

2025-01-10 17:26 UTC, andrablaj commented on content/en/building/guides/interoperability/openhim.md
> +1. Run `./startup.sh init` to start-up the docker containers on the first run or after calling `./startup.sh destroy`. Use `./startup.sh up` for subsequent runs after calling `init` without calling `
```suggestion
In the cht-interoperability folder, run `./startup.sh init` to start up the docker containers on the first run or after calling `./startup.sh destroy`. Use `./startup.sh up` for subsequent runs after calling `init` without calling `destroy`.
```

2025-01-10 17:27 UTC, andrablaj commented on content/en/building/guides/interoperability/openhim.md
> +The following steps apply when running CHT via the Docker setup provided in this repository:
```suggestion
The following steps apply when running CHT via the Docker setup provided in the cht-interoperability repository:
```

2025-01-10 17:28 UTC, andrablaj commented on content/en/building/guides/interoperability/openhim.md
> +- `Postman` or similar tool for API testing.
```suggestion
- `Postman` or similar tool for API testing.
- [cht-interoperability](https://github.com/medic/cht-interoperability) GitHub repository (can be cloned via `git clone https://github.com/medic/cht-interoperability`).
```

2025-01-10 17:34 UTC, andrablaj commented on content/en/building/guides/interoperability/openhim.md
> +### Install & First Time Run
```suggestion

{{% alert title="Note" %}} 
Users getting errors when running the following installation steps, please see the [Troubleshooting guide]({{< ref "#troubleshooting" >}}).
{{% /alert %}}

### Install & First Time Run
```

2025-01-10 17:35 UTC, andrablaj commented on content/en/building/guides/interoperability/openhim.md
> +1. Once logged in, visit [http://localhost:9000/#!/mediators](http://localhost:9000/#!/mediators) and select the only mediator with the `Name` 'Loss to Follow Up Mediator'.
```suggestion
1. Once logged in, visit [http://localhost:9000/#!/mediators](http://localhost:9000/#!/mediators) and select the only mediator with the `Name` "Loss to Follow Up Mediator".
```

2025-01-10 17:36 UTC, andrablaj commented on content/en/building/guides/interoperability/openhim.md
> +3. Securely save the `interop-client` user's password to the database using the instructions [here]({{< ref "building/reference/api#credentials" >}}). Change the values `mykey` and `my pass` to `open
```suggestion
3. Securely save the `interop-client` user's password to the database using the instructions [here]({{< ref "building/reference/api#credentials" >}}). Change the values `mykey` and `my pass` to `openhim1` and your user's password respectively. An example of the curl request is below:
```

2025-01-10 17:38 UTC, andrablaj commented on content/en/building/guides/interoperability/openhim.md
> +4. After updating the mediator code or cht configuration, you need to run `./startup.sh up-dev` to upload the changes to docker compose.
```suggestion
4. After updating the mediator code or the CHT configuration, you need to run `./startup.sh up-dev` to upload the changes to docker compose.
```

2025-01-10 17:39 UTC, andrablaj commented on content/en/building/guides/interoperability/openmrs.md
> +1. Set up a test environment including an OpenMRS instance, a CHT instance, and OpenHIM. The [interoperability project](https://github.com/medic/cht-interoperability) has docker compose files so that
```suggestion
1. Set up a test environment including an OpenMRS instance, a CHT instance, and OpenHIM. The [interoperability project](https://github.com/medic/cht-interoperability) has docker compose files so that you can set this up locally by running `./startup.sh up-openmrs` in the interoperability project.
```

2025-01-10 17:49 UTC, lorerod commented
> It would be lovely if someone could go through the OpenMRS setup steps (@lorerod, @mrjones-plip ?) to validate the clarity of the instructions. I will try to do this myself next week, but I don't want to be a blocker to having this merged.

@andrablaj, I have a pending re-review of this PR, and I will follow the OpenMRS setup steps next week.

2025-01-13 10:36 UTC, witash commented on content/en/building/guides/interoperability/ltfu.md
> +1.  Create a **Patient**
apparently adding a note does break the list. Changed to number the other elements explicitly

2025-01-16 20:43 UTC, lorerod requested changes
Thank you for the effort you've put into this documentation. I’m reviewing it by reproducing the steps on my local machine using the [cht-interoperability openmrs-mediator](https://github.com/medic/cht-interoperability/tree/openmrs-mediator) branch.

2025-01-16 20:43 UTC, lorerod commented on content/en/building/guides/interoperability/openmrs.md
> +1. A request to the FHIR server updating the encounter with the corresponding id from OpenMRS.
Ok, after creating the CHT report, I see only two POST request and then all GET. 
This is how the transaction logs looks like:
![image](https://github.com/user-attachments/assets/24ce5c6a-4075-43be-8e57-188c3499f7c8)

2025-01-16 20:43 UTC, lorerod commented on content/en/building/guides/interoperability/openmrs.md
> +When sending form data to CHT, first find, create, or import the concepts in OpenMRS, and create the forms in OpenMRS.
If there are instructions on how to do this, that would be great. Maybe a link to the OpenMRS page?

2025-01-16 20:43 UTC, lorerod commented on content/en/building/guides/interoperability/openmrs.md
> +Then create a form in CHT to receive the reports [as described in the CHT interop config documentation]({{< ref "building/guides/interoperability/cht-config#outbound-reports" >}}); the codes from Ope
If this is pre-configured in the cht-interoperability repository, please include a notice here.

2025-01-20 09:57 UTC, witash commented on content/en/building/guides/interoperability/openmrs.md
> +1. Set up a test environment including an OpenMRS instance, a CHT instance, and OpenHIM. The [interoperability project](https://github.com/medic/cht-interoperability) has docker compose files so that
added cht-config resources created by `./startup.sh up-openmrs` in the OpenHIM resources section below

2025-01-20 09:57 UTC, witash commented on content/en/building/guides/interoperability/openmrs.md
> +After setting up the outbound push config, test that it works in the test environment by creating a patient in the CHT application.
added cht-config resources created by `./startup.sh up-openmrs` in the OpenHIM resources section below

2025-01-20 09:57 UTC, witash commented on content/en/building/guides/interoperability/openmrs.md
> +After setting up the outbound push, test that it works in the test environment by submitting a report to the form in the CHT application.
added cht-config resources created by `./startup.sh up-openmrs` in the OpenHIM resources section below

2025-01-20 18:08 UTC, lorerod approved these changes
Approving this PR to unblock as the documentation aligns with what is expected, and we will address the pending issues in separate, independent tickets.

2025-01-20 18:08 UTC, lorerod commented on content/en/building/guides/interoperability/openmrs.md
> +1. A request to the FHIR server updating the encounter with the corresponding id from OpenMRS.
Resolving this conversation as I created [this](Failure to Sync Encounters and Observations from CHT to OpenMRS via Mediator](https://github.com/medic/cht-interoperability/issues/157#top) issue to follow up

2025-01-27 09:03 UTC, merged