update default behavior of appliesToType
medic/cht-docs pull request #300
Opened 2020-09-02 17:47 UTC by njogz

Update documentation to better describe the default behavior introduced in this [PR](https://github.com/medic/medic-conf/pull/361)

2020-09-02 22:30 UTC, garethbowen requested changes
Nice! One comment inline.

2020-09-02 22:30 UTC, garethbowen commented on content/en/apps/reference/contact-page.md
> +| `appliesToType` | `string[]` | Filters the contacts for which `appliesIf` will be evaluated. For example, `['person']` or `['clinic', 'health_center']`. It defaults to all types if it is not define
Nice! I think we also need to update the Condition Cards documentation on line 56.

2020-09-03 21:55 UTC, garethbowen approved these changes
Nice!

2021-04-20 13:35 UTC, abbyad commented
Is this PR ready to merge now that https://github.com/medic/medic-conf/issues/164 is closed?

2021-06-02 06:29 UTC, merged