add reference to xpath functions
medic/cht-docs pull request #329
Opened 2020-10-01 15:33 UTC by newtewt

I think this probably could be better but is very bare minimum. I couldn't think of better words this morning to describe what the functions do.  A more in depth ticket about using functions, operators, and maybe a guide on using calculations might be a future ticket.

2020-10-02 11:46 UTC, njogz approved these changes
Looks good.

2020-10-02 15:11 UTC, abbyad requested changes
Nice additions Nick. I made suggested edits in the comment to update some older text in that section.

2020-10-02 15:11 UTC, abbyad commented on content/en/apps/reference/forms/app.md
> +Read more about the [XPath specification](https://www.w3.org/TR/xpath/)
While we are here taking the opportunity to clarify and revise older text:

```suggestion
Calculations are achieved within app forms using XPath statements in the "calculate" field of XForms and XLSForms. CHT apps support XPath from the [ODK XForm spec](https://getodk.github.io/xforms-spec), which is based on a subset of [XPath 1.0](https://www.w3.org/TR/1999/REC-xpath-19991116/), and is evaluated by [`medic/openrosa-xpath-evaluator`](https://github.com/medic/openrosa-xpath-evaluator). The ODK XForm documentation provides useful notes about the available [operators](https://getodk.github.io/xforms-spec/#xpath-operators) and [functions](https://getodk.github.io/xforms-spec/#xpath-functions). Additionally, [CHT specific functions](#cht-xpath-functions) are available for forms in CHT apps.

{{% alert title="Note" %}} 
The `+` operator for string concatenation is deprecated and will be removed in a future version. You are strongly encouraged to use the [`concat()`](https://getodk.github.io/xforms-spec/#fn:concat) function instead. 
{{% /alert %}}
```

2020-10-02 16:17 UTC, abbyad approved these changes

2020-10-05 22:30 UTC, garethbowen approved these changes
Merge when ready.

2020-10-06 11:43 UTC, merged