add targets tutorial
medic/cht-docs pull request #349
Opened 2020-10-14 09:40 UTC by smbuthia

https://github.com/medic/cht-docs/issues/342

2020-10-21 12:59 UTC, kitsao requested changes
Like the precision. 1 inline comment.

2020-10-21 12:59 UTC, kitsao commented on content/en/apps/tutorials/targets.md
> +Edit the `target.js` file and add another target widget definition object to define a monthly widget as shown below:
`targets.js`

2020-10-22 07:22 UTC, smbuthia commented on content/en/apps/tutorials/targets.md
> +Edit the `target.js` file and add another target widget definition object to define a monthly widget as shown below:
Updated.

2020-10-23 06:09 UTC, kitsao approved these changes

2020-10-23 06:17 UTC, merged