Updated references to Medic Mobile
medic/cht-docs pull request #444
Opened 2021-03-03 19:00 UTC by abbyad

2021-03-03 19:40 UTC, abbyad commented
Apologies for the spammy review request, this PR covered a lot of code owners! Only one reviewer needed here, @mrjones-plip can you review this?

2021-03-03 20:17 UTC, mrjones-plip commented
Yes, will grab today!

2021-03-03 20:51 UTC, mrjones-plip commented on content/en/apps/guides/messaging/gateway/phones.md
> -In order to implement the Medic Mobile Standard package at your site, you will require an Android device for the Medic gateway. You may use an existing Android device and are not required to purchase
much improved! nice work.

2021-03-03 20:55 UTC, mrjones-plip requested changes
I think you got them all but one! See `content/en/core/overview/translations.md`:

```
➜  cht-docs git:(443-rename-medic-mobile) grep -r 'Medic Mobile' content/en               
content/en/core/overview/translations.md:If you don't have an API token, please contact a Medic Mobile developer, product manager, or CTO. Please do not disclose this API token to anyone else.
```

2021-03-03 21:06 UTC, mrjones-plip commented
Oh weird, that `translations.md` change I requested, is [actually covered here](https://github.com/medic/cht-docs/pull/444/files#diff-79fc16fa5b66994daa2f1c0518e4af70d6b3fdb4c3b27eec2b24c591c73048c5L64), but I'm still seeing it on disk in the branch?!  I'll approve this PR and we can see if it's still there when we're all back on `master`.  sorry for the confusion!

2021-03-03 21:08 UTC, mrjones-plip approved these changes
approved as long as we check the [one on translations](https://docs.communityhealthtoolkit.org/core/overview/translations/#exporting-changes-from-poeditor-to-github) after it's live!

2021-03-03 21:27 UTC, merged

2021-03-04 00:26 UTC, abbyad commented
Confirming that the one one translations is all good.

2021-03-04 00:35 UTC, mrjones-plip commented
@abbyad  is good or not good?  You want it to still say "Medic Mobile"?

> please contact a Medic Mobile developer, product manager, or CTO.

The [line in the PR](https://github.com/medic/cht-docs/pull/444/files#diff-79fc16fa5b66994daa2f1c0518e4af70d6b3fdb4c3b27eec2b24c591c73048c5L64) was there to change this line to simply:

> please contact a Medic developer.

but for some reason the first text above is [what's live](https://docs.communityhealthtoolkit.org/core/overview/translations/#exporting-changes-from-poeditor-to-github) (and [in master](https://github.com/medic/cht-docs/blob/master/content/en/core/overview/translations.md#adding-new-keys), obvs.), not the second (still baffled why!?).

2021-03-04 00:39 UTC, abbyad commented
Ah, it was in two places 🤦

2021-03-04 00:42 UTC, abbyad commented
Thanks for catching that. I have fixed it in https://github.com/medic/cht-docs/pull/445