change to object and added note about capitalization
medic/cht-docs pull request #497
Opened 2021-05-14 17:10 UTC by newtewt

#496 
#495

2021-05-19 00:21 UTC, abbyad requested changes
Good to have these changes included!

Suggestion inline, but it may be a matter of preference. If you feel strongly I am happy to approve as is.

2021-05-19 00:21 UTC, abbyad commented on content/en/apps/reference/app-settings/forms.md
> +JSON forms are defined in either the `base_settings.json` or the `app_settings/forms.json` file and compiled in to the `app_settings.json` file with the `compile-app-settings` action in the `medic-co
Would be good to clarify that it is the entire string that needs to be uppercase, and I also think uppercase will reasonate more than capitalized to say that. 

```suggestion
JSON forms are defined in either the `base_settings.json` or the `app_settings/forms.json` file and compiled in to the `app_settings.json` file with the `compile-app-settings` action in the `medic-conf` tool. JSON Forms are used for parsing reports from formatted SMS, SIM applications, and Medic Collect. JSON form definitions are also used for interoperability with third-party systems. Each form is defined as an JSON form object according to the following schema. The key for each object must be unique and all characters must be uppercase. 
```

2021-06-01 17:36 UTC, newtewt commented
@abbyad  I think your suggestion makes sense. I committed and just need an approval.

2021-06-01 17:38 UTC, abbyad approved these changes
Looks great, thanks for making the corrections that will surely save someone headaches and time down the line!

2021-06-01 17:38 UTC, merged