Add permissions and UHC docs
medic/cht-docs pull request #516
Opened 2021-06-11 17:19 UTC by eljhkrr

https://github.com/medic/cht-docs/issues/400
https://github.com/medic/cht-docs/issues/82

2021-06-16 14:03 UTC, smbuthia requested changes
Thanks for adding these. I've added some comments/suggestions inline.

2021-06-16 14:03 UTC, smbuthia commented on content/en/apps/reference/app-settings/user-permissions.md
> +Each permission is defined in terms of an array of user role identifiers that have the permission granted.
```suggestion
Each permission is defined as an array of user role identifiers that have the permission granted.
```

2021-06-21 07:37 UTC, eljhkrr commented on content/en/apps/guides/forms/uhc-mode.md
> +![UHC mode](UHC.gif)
Updated

2021-06-21 07:38 UTC, eljhkrr commented on content/en/apps/guides/forms/uhc-mode.md
> +![Contact sort](person-contact-form-survey.png)
Updated

2021-06-23 11:32 UTC, smbuthia commented on content/en/apps/guides/forms/uhc-mode.md
>  The date last visited is colored red whenever the date is 30 days or more in the past. The date last visited is displayed as a relative date. Visits that happened today will say "Visited today", visi
```suggestion 
{{< figure src="UHC.gif" link="UHC.gif" alt="UHC mode screenshot" class="right col-6 col-lg-3" >}}

UHC mode empowers CHWs to provide equitable and timely care to families in their catchment area. The Community Health Toolkit supports this use-case by displaying the number of
visits made to a household and highlighting households that haven't met their visit goal in red at the top of the contact list.

The date last visited is colored red whenever the date is 30 days or more in the past. The date last visited is displayed as a relative date. This period is described in terms of "days" up until two months, so "Visited 3 days ago" or "Visited 36 days ago". After two months, we simply say "2 months" or "3 months".
```

2021-06-23 11:35 UTC, smbuthia commented on content/en/apps/guides/forms/uhc-mode.md
> +{{< figure src="sort-dropdown.png" link="sort-dropdown.png" alt="Contact sorting screenshot" title="Contact sorting in UHC mode" >}}
```suggestion
### Sorting

{{< figure src="sort-dropdown.png" link="sort-dropdown.png" alt="Contact sorting screenshot" class="right col-6 col-lg-3" >}}

The date of the last visit is displayed and contacts can be sorted by the last visit date to allow the CHW to plan their work.
```

2021-06-23 14:41 UTC, eljhkrr commented on content/en/apps/guides/forms/uhc-mode.md
>  The date last visited is colored red whenever the date is 30 days or more in the past. The date last visited is displayed as a relative date. Visits that happened today will say "Visited today", visi
Updated

2021-06-23 14:41 UTC, eljhkrr commented on content/en/apps/guides/forms/uhc-mode.md
> +{{< figure src="sort-dropdown.png" link="sort-dropdown.png" alt="Contact sorting screenshot" title="Contact sorting in UHC mode" >}}
Updated

2021-06-23 14:49 UTC, smbuthia approved these changes
Looks good. Thanks.

2021-06-23 15:29 UTC, merged