6981 - documentation for android-app-launcher, display-base64-image and parse-timestamp-to-date
medic/cht-docs pull request #540
Opened 2021-08-14 14:52 UTC by latin-panda

**Description**

This PR:
- Adds documentation for display-base64-image widget.
- Adds documentation for android-app-launcher widget.
- Adds documentation for parse-timestamp-to-date xpath function.

Ticket: https://github.com/medic/cht-core/issues/6981

[CHT-Core](https://github.com/medic/cht-core/pull/7248)
[CHT-Android](https://github.com/medic/cht-android/pull/199)

**License**

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

2021-08-14 14:55 UTC, latin-panda commented
Hi @garethbowen, can you please review? Thank you for your time!

2021-08-15 23:00 UTC, garethbowen requested changes
Very detailed documentation. I've left a couple of grammatical suggestions inline as well as a clarification about what happens in a browser.

2021-08-16 03:17 UTC, latin-panda commented on content/en/apps/reference/forms/app.md
> +Use the Android App Launcher widget in an app form to configure an Android intent to launch an app installed in the mobile device, the widget will send values from input fields type `text` to the app
Done!

2021-08-16 03:17 UTC, latin-panda commented on content/en/apps/reference/forms/app.md
> +To define the widget, create a `group` with the appearance `android-app-launcher`, then define the [Android intent](https://developer.android.com/reference/android/content/Intent) fields with type `t
Done!

2021-08-16 03:17 UTC, latin-panda commented on content/en/apps/reference/forms/app.md
> +_Available in +3.13.0 and in Android device only_
Nice, done!

2021-08-16 04:27 UTC, garethbowen approved these changes
Nice one!

2021-09-15 15:22 UTC, merged