doc: 6 installation steps for rapidpro cht apk
medic/cht-docs pull request #550
Opened 2021-09-16 09:58 UTC by freefony

2021-09-24 07:17 UTC, smbuthia requested changes
Thanks for adding this guide. Some changes suggested. Are there some additional tips or tricks that you could add on here to flesh it out a little more?

2021-09-24 07:17 UTC, smbuthia commented on content/en/apps/guides/messaging/gateways/rapidpro_cht_gateway.md
> +#
Add [front matter](https://gohugo.io/content-management/front-matter/) with at least; title, linkTitle, and description.

2021-09-24 07:17 UTC, smbuthia commented on content/en/apps/guides/messaging/gateways/rapidpro_cht_gateway.md
> +Due to restrictions Android has on applications that send SMS messages, we cannot distribute the RapidPro - CHT application through the Play Store. You will need to download the application manually
I think it's more accurate to state that the restrictions are from Google on Android applications. I'd rephrase this a bit.
```suggestion
Due to restrictions that Google has placed on Android applications that send SMS messages, RapidPro - CHT applications can no longer be distributed through the Google Play Store. You will need to download the application file and install it using the steps below:
```

2021-09-24 07:17 UTC, smbuthia commented on content/en/apps/guides/messaging/gateways/rapidpro_cht_gateway.md
> +![download](rapidpro/apk_download.png "image_tooltip")
The images are not getting rendered. Have a look at the [documentation on image processing](https://gohugo.io/content-management/image-processing/) to guide you on how to add images.

2022-07-04 01:50 UTC, garethbowen commented
@freefony Can you please review the suggestions Sam made so we can get these improvements merged?

2022-11-24 21:58 UTC, garethbowen commented
@mrjones-plip "randomly" picked you as the new reviewer... please have a look or reassign!

2022-11-30 18:56 UTC, mrjones-plip requested changes
Great to see more info on RapidPro  - thanks!

Let's start with three changes and then I can more easily review the PR:
1. rename `rapidpro` directory to `rapidpro_cht_gateway`
2. remove  unused `rapidpro/_index.md` file
3. Fix images so they correctly load in `rapidpro_cht_gateway.md` per [docs on images](https://docs.communityhealthtoolkit.org/contribute/docs/style-guide/#images). 

This will fix the dupe in the left navigation which shows an mostly empty page when you click. Arrow shows link to actual content:
![image](https://user-images.githubusercontent.com/8253488/204885032-07fd7e69-c23c-4de0-82ab-e27fbfea0463.png)

2023-08-06 23:57 UTC, garethbowen commented
@freefony Just checking in here - are you free to review the last few changes mrjones suggested?

2024-04-25 11:09 UTC, garethbowen commented
@mrjones-plip Can you revive this please and either make the suggested improvements yourself or close the PR as dead?

2024-04-29 22:46 UTC, merged

2024-04-29 22:47 UTC, mrjones-plip commented
thanks for the nudge @garethbowen !

@freefony - if you see any mistakes now that this is live, please open a new PR to fix.