CHT Gateway Doc Update
medic/cht-docs pull request #579
Opened 2021-11-22 16:10 UTC by billwambua

Make CHT Gateway doc easier to follow and correct spelling mistakes.

2021-11-23 00:58 UTC, garethbowen requested changes
Thanks! A couple of small suggestions inline.

Also, it looks like you've added an image but haven't included it in the page anywhere?

2021-11-23 00:58 UTC, garethbowen commented on content/en/apps/guides/messaging/gateways/gateway/configuration.md
> +3. Configure the app. If you're configuring cht-gateway(v1.00 and above) for use with hosted medic, with a URL of e.g. ```https://myproject.dev.medicmobile.org``` and a username of ```gateway``` and
I think the version should be `1.0.0` like it was before. `1.00` looks weird to me!

```suggestion
3. Configure the app. If you're configuring cht-gateway(v1.0.0 and above) for use with hosted medic, with a URL of e.g. ```https://myproject.dev.medicmobile.org``` and a username of ```gateway``` and a password of ```topSecret```, fill in the settings as follows:
```

2021-11-23 00:58 UTC, garethbowen commented on content/en/apps/guides/messaging/gateways/gateway/configuration.md
> +Username: `gateway`(_Since_ [V1.2.1](https://github.com/medic/cht-gateway/releases/tag/v1.2.1) _medic gateway versions this field is not present in the app. The user `gateway` is assumed_.)<br>
Minor suggestion...

```suggestion
Username: `gateway`(_Since_ [v1.2.1](https://github.com/medic/cht-gateway/releases/tag/v1.2.1) _medic gateway versions this field is not present in the app. The user `gateway` is assumed_.)<br>
```

2021-11-25 09:27 UTC, billwambua commented
> Thanks! A couple of small suggestions inline.
> 
> Also, it looks like you've added an image but haven't included it in the page anywhere?

About the image, what I did was replace the existing image(`gateway-config.png`) with a screenshot of the newest CHT-Gateway version.

2021-11-25 19:01 UTC, garethbowen approved these changes
Awesome, thanks!

2021-11-25 19:01 UTC, merged

2021-11-26 17:25 UTC, kennsippell commented
Nice one @billwambua!