update documentation to add new can_upgrade permission
medic/cht-docs pull request #653
Opened 2022-03-17 07:23 UTC by njogz

2022-03-17 20:15 UTC, garethbowen requested changes
One minor change suggested.

2022-03-17 20:15 UTC, garethbowen commented on content/en/apps/reference/app-settings/user-permissions.md
> +| `can_upgrade` | Allows upgrade of the CHT instance |
`upgrade` here could be mistaken for workflow upgrades, ie: configuration. How about we change it to...

```suggestion
| `can_upgrade` | Allows upgrades of the CHT Core Framework version via the API or admin interface |
```

2022-03-21 20:16 UTC, garethbowen approved these changes
Thanks!

2022-04-04 17:14 UTC, mrjones-plip commented
@njogz  - can you merge to `main` if this is ready to go? Thanks!

2022-04-04 17:20 UTC, mrjones-plip commented
Oh - oops! Maybe you're waiting for code issue to close? I thought it had passed AT, but I see now it's back in dev for some improvements.   No biggie!

2022-05-03 02:13 UTC, merged