moves rapidpro best practices to under guide
medic/cht-docs pull request #706
Opened 2022-06-06 10:21 UTC by kitsao

Closes #628

2022-06-09 01:30 UTC, abbyad commented on content/en/apps/guides/integrations/rapidpro.md
> +The following are best practices when working on a RapidPro deployment to integrate with the CHT. Review RapidPro’s documentation to familiarize yourself with various components that include the [API
This can be largely eliminated, and the parts introducing RapidPro and it's API can be added to the top level intro paragraph.

2022-06-15 09:58 UTC, kitsao commented
Not sure I get the aliasing aspect, since I removed `apps/guides/integrations/best-practices`.

2022-06-16 02:51 UTC, abbyad requested changes
Looks good!

If someone in the future tries to go to `apps/guides/integrations/best-practices`, where should they land? From a quick look that might be `apps/guides/integrations/_index.md`. On that page, you'll need to add an alias to the removed index page. Otherwise old links, including from search engines will 404.

With the alias and the fixed typo I think it'll be good to go!

2022-06-16 02:51 UTC, abbyad commented on content/en/apps/guides/integrations/rapidpro.md
> +[RapidPro](https://app.rapidpro.io/) is the open-source platform that powers [TextIt](https://textit.com/), developed by UNICEF and Nyaruka. RapidPro allows you to visually build messaging workflows
Adds missing word from original text.

```suggestion
[RapidPro](https://app.rapidpro.io/) is the open-source platform that powers [TextIt](https://textit.com/), developed by UNICEF and Nyaruka. RapidPro allows you to visually build messaging workflows for mobile-based services. Review RapidPro’s documentation to familiarize yourself with various components that include the [API](https://rapidpro.io/api/v2/). Before you embark on designing an integrated RapidPro/CHT workflow, you should start by understanding the needs of your users, identifying a problem to solve, and establishing goals. While an integrated RapidPro/CHT workflow can open up many powerful and personalized messaging capabilities, introducing an additional technology solution does come with complexities and cost. A good way to mitigate some of the complexities of setting up and [hosting](https://rapidpro.github.io/rapidpro/docs/hosting/) RapidPro yourself is to utilize a SaaS solution such as [TextIt](https://textit.in/). TextIt offers transparent per message [pricing](https://textit.in/pricing/) and free credits to start off.
```

2022-06-29 16:04 UTC, abbyad commented
I don't know where I saw the `apps/guides/integrations/best-practices/rapidpro` earlier, but I can't find it now... I'll edit the aliases for your review.

2022-06-29 16:08 UTC, abbyad commented
@kitsao please review the alias changes. With that I think you should be ready to go!

2022-06-29 16:09 UTC, abbyad approved these changes

2022-07-05 01:16 UTC, merged