Document bulk user upload
medic/cht-docs pull request #727
Opened 2022-07-12 11:50 UTC by m5r

2022-07-21 18:28 UTC, mrjones-plip requested changes
Yowza - this looks awesome!  thanks for this.

I'll need to dive in deeper, but right away I see two changes we need:
* please use english screenshots, not french. I think you can easily grab the english ones [from here](https://docs.google.com/document/d/1HwyZUl6w8YEEK6W9r4qMn_0nzrujHKeHNq5-49dzICg/edit#heading=h.bt4f1ry64jmk)
* We need to specify this will only work in 3.16 or later

more to come!

2022-07-25 13:09 UTC, m5r commented
> - please use english screenshots, not french. I think you can easily grab the english ones [from here](https://docs.google.com/document/d/1HwyZUl6w8YEEK6W9r4qMn_0nzrujHKeHNq5-49dzICg/edit#heading=h.bt4f1ry64jmk)
> - We need to specify this will only work in 3.16 or later

Done and done, thanks @mrjones-plip  
You really did a great job documenting the steps to use this feature!

2022-07-25 17:53 UTC, mrjones-plip commented
Awesome! I'll dive back into this today or tomorrow.

2022-07-26 00:00 UTC, mrjones-plip requested changes
Yay - getting closer!

I did another pass on the content and made some suggestions.  Biggest missing piece of content I think is the API area for the bare minimum set of fields to create different objects.  See comments. 

Also, looking over the images, I see we need to redo them as they're incongruous and  reference some specific deployments by name and specific, real geographic places.  I'll do this tomorrow!

2022-07-27 01:18 UTC, mrjones-plip commented
I uploaded new screenshots all with a 1px border, all on the same dataset.

2022-08-01 21:57 UTC, mrjones-plip commented
@m5r  - we should try and push this through before 3.16 goes live! Lemme know if you wanna do a real-time session to save on some back and forth time on the PR

2022-08-02 13:40 UTC, m5r commented on content/en/apps/reference/api.md
> +
That would be the [Supported Properties](https://docs.communityhealthtoolkit.org/apps/reference/api/#supported-properties-2) section in the Users section. I agree they could use some love, I had to rely on the implementation and some examples to find what fields I can use in the `contact` and `place` properties.

Do we have an example of documentation where we list out all the possible fields with nested properties?

2022-08-03 15:18 UTC, mrjones-plip approved these changes
While I do think we should document all the possible fields, I think what we have is usable and accurate.  Let's ship this and iteratively improve on it.

I think a good next iteration would be a example spreadsheets that show how to just add users and just add users and contacts.  In conjunction with the one we have, this will give users a great working example on how each works.

We can revisit the exhaustive list fields!

excellent work on seeing this through - thank you!

2022-08-03 16:42 UTC, merged