Add horti links, use  beta1 example of install
medic/cht-docs pull request #757
Opened 2022-08-25 23:19 UTC by mrjones-plip

2022-11-24 21:56 UTC, garethbowen commented
@mrjones-plip Where is this PR at?

2022-11-30 05:34 UTC, mrjones-plip commented
Thanks for the nudge @garethbowen ! I'd clearly forgotten about this - looks good to go (but you tell me ;)

2022-11-30 20:07 UTC, garethbowen requested changes
One typo suggestion inline. I'm not comfortable adding a new section with "TK" as the content - let's just leave that out until it's written?

Obviously we'll have to update this soon with 4.x info (eg: no horti) but that can be done in a separate PR.

2022-11-30 20:07 UTC, garethbowen commented on content/en/core/releases/feature_releases.md
> +When you are on a non-feature release, you need to use horticulturalist (horti) to do the initial install of the FR.  For example, if your instance was runnint at `192-168-68-26.my.local-ip.co:8443`
```suggestion
When you are on a non-feature release, you need to use horticulturalist (horti) to do the initial install of the FR.  For example, if your instance was running at `192-168-68-26.my.local-ip.co:8443` and you wanted to install `3.16.0-FR-offline-user-replace-beta.1`, after [installing](https://github.com/medic/horticulturalist#usage) `horti` you could start the installation with this command:
```

2022-11-30 21:07 UTC, mrjones-plip commented on content/en/core/releases/feature_releases.md
> +TK
agreed! missed this when I sent it to you for review.  thanks for catching it!  Fixed in 504b25c0915cb04d6bfde04265ae2408e9342b09

2022-11-30 21:13 UTC, garethbowen approved these changes

2022-11-30 21:14 UTC, merged