Split 3.x hosting docs off, create 4.x hosting section
medic/cht-docs pull request #812
Opened 2022-10-21 18:38 UTC by mrjones-plip

2022-10-24 08:09 UTC, esthermmoturi approved these changes

2022-10-24 22:02 UTC, garethbowen requested changes
Great first step, thanks! A couple of suggestions inline.

2022-10-24 22:02 UTC, garethbowen commented on content/en/apps/tutorials/local-setup.md
>  To install a valid certificate, open a terminal in the `cht-core` directory. Ensure the `medic-os` container is running and make this call:
We should drop references to `medic-os` while we're here.

```suggestion
To install a valid certificate, open a terminal in the `cht-core` directory. Ensure the CHT instance is running and make this call:
```

2022-10-31 20:39 UTC, mrjones-plip commented on content/en/apps/guides/updates/preparing-for-4.md
> +An easy way of doing this is to use the [CHT Docker Helper]({{< relref "apps/guides/hosting/3.x/app-developer#cht-docker-helper" >}}) to deploy a 3.x CHT instance. After you have your dev instance up
D'oh! Fixed in 458dee8

2022-10-31 21:27 UTC, garethbowen approved these changes
Awesome, thanks.

2022-10-31 21:34 UTC, merged