Update core developer setup for CHT 4.x
medic/cht-docs pull request #848
Opened 2022-11-15 12:46 UTC by andrablaj

Closes #837

2022-11-15 20:20 UTC, garethbowen requested changes
Great work, thanks.

A few suggestions inline, and it may be worth investigating whether we should run the 3.x development against a 4.x couchdb image so it does the securing automatically. I think this would greatly simplify things but obviously will need some testing!

2022-11-15 20:20 UTC, garethbowen commented on content/en/apps/guides/hosting/core-developer.md
> +Copy the content of the CouchDB `docker-compose` file from the of the CHT release version you are trying to run locally. For example, this is [the file](https://staging.dev.medicmobile.org/_couch/bui
As discussed on the call, let's link to `master` so the developer gets the latest image when setting up.

```suggestion
Copy the content of the CouchDB `docker-compose` file from the of the CHT release version you are trying to run locally. For example, this is [the file](https://staging.dev.medicmobile.org/_couch/builds_4/medic%3Amedic%3Amaster/docker-compose%2Fcht-couchdb-clustered.yml) for the most recent build.
```

2022-11-16 13:26 UTC, andrablaj commented on content/en/apps/guides/hosting/core-developer.md
> +
Good idea, thanks!

2022-11-16 20:50 UTC, garethbowen approved these changes
Looks great, thanks for taking the time!

2022-11-17 07:13 UTC, merged