Single node self hosting docs
medic/cht-docs pull request #915
Opened 2022-12-15 10:32 UTC by henokgetachew

First PR for [this](https://github.com/medic/cht-docs/issues/831) ticket.

2022-12-15 12:21 UTC, garethbowen requested changes
Awesome work, thanks! A few suggestions inline.

2022-12-15 12:21 UTC, garethbowen commented on content/en/core/overview/self-hosting-single-node.md
> +---
Please move this to beside the other hosting docs here: https://docs.communityhealthtoolkit.org/apps/guides/hosting/4.x/

2022-12-15 12:21 UTC, garethbowen commented on content/en/core/overview/self-hosting-single-node.md
> +Follow the set of steps outlined [here](https://github.com/medic/cht-core/pull/7834#issuecomment-1268710481).
Let's convert this issue comment to a docs page and then link from here and the multi-node docs. If it's not trivial then feel free to raise an issue to do that one later.

2023-01-19 22:20 UTC, mrjones-plip commented
closing  this one in favor of a single PR in #916 - will move this content there

2023-01-19 22:20 UTC, closed without merging