Cht academy overview doc
medic/cht-docs pull request #929
Opened 2023-01-06 11:54 UTC by esthermmoturi

Draft PR for CHT academy documentation

2023-01-12 13:12 UTC, craig-landry requested changes
Sometimes I see pages and sections like this and they feel unnecessary, but then I'll end up seeing people struggle to find where to start. It's easy for us to assume everyone will get it, but that's often not true. With that, thanks for adding this stuff! I think it'll make more of a difference than we might expect.

I made a few small comments, but know this is a draft, so I assume things will get tidied up. In general: good stuff!

2023-01-12 13:12 UTC, craig-landry commented on content/en/apps/tutorials/local-setup.md
> +If you are using an older version of cht-core, ensure that the  `add-local-ip-certs-to-docker.sh` file is available under the scripts folder.
This line looks unrelated to the concept of an overview. Please remove it from this PR and open a separate one so we can review separately and keep things clear in the git history.

2023-01-12 13:12 UTC, craig-landry commented on content/en/apps/tutorials/cht-academy.md
> +weight: 5
Please make sure this shows up first within the Tutorials section. I think it makes sense for people to see this before other tutorial content.

2023-03-14 03:40 UTC, nsitaula commented
Hi @esthermmoturi is there anything needed from me? I noticed @craig-landry reviewed and suggested some updates.

2023-10-06 05:40 UTC, closed without merging