Including information about angular upgrade exception
medic/cht-docs pull request #942
Opened 2023-01-17 05:29 UTC by latin-panda

# Description

Includes more information about an exception when upgrading webapp's angular and a tip to fix it. Also, more information about upgrading lodash library.
 
# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

2023-01-17 05:30 UTC, latin-panda commented
Hi @esthermmoturi, can you please review? Thanks

2023-01-19 06:18 UTC, esthermmoturi requested changes

2023-01-19 06:18 UTC, esthermmoturi commented on content/en/contribute/code/core/update-dependencies.md
> +- Don't update `lodash` to version `4.17.21`, there's a runtime issue when importing `lodash/core` in Admin app:
Don't update `lodash` to version `4.17.21`. If you do so, the runtime issue highlighted below will appear when importing `lodash/core` in Admin app:

2023-01-19 06:18 UTC, esthermmoturi commented on content/en/contribute/code/core/update-dependencies.md
> +  In their code, the issue is here:
The issue on the code is here:

2023-01-19 06:18 UTC, esthermmoturi commented on content/en/contribute/code/core/update-dependencies.md
> +  There was an [open issue](https://github.com/lodash/lodash/issues/4904) in their repository but got deleted (reason unknown). There's [another reported issue](https://github.com/lodash/lodash/issue
There was an [open issue](https://github.com/lodash/lodash/issues/4904) in the lodash repository but got deleted (reason unknown). There's [another reported issue](https://github.com/lodash/lodash/issues/4945) explaining the problem, however it hasn't been resolved yet.

2023-01-19 06:20 UTC, esthermmoturi commented on content/en/contribute/code/core/update-dependencies.md
> +- Don't update `lodash` to version `4.17.21`, there's a runtime issue when importing `lodash/core` in Admin app:
You can add this

2023-01-19 08:15 UTC, latin-panda commented
Thanks for the feedback @esthermmoturi, can you please have a look again?

2023-01-19 08:44 UTC, esthermmoturi approved these changes

2023-01-21 04:12 UTC, merged