Update local-setup.md
medic/cht-docs pull request #952
Opened 2023-02-01 08:10 UTC by Phil-Mwago

For more context, we had this issue here on the forum: https://forum.communityhealthtoolkit.org/t/unable-to-push-and-upload-a-blank-project-on-my-local-environment/2427/8

My local set up has issues deploying a blank project on the cht-core location. We replicated this in other local deployments.

2023-02-10 17:21 UTC, craig-landry approved these changes

2023-02-10 17:21 UTC, craig-landry commented on content/en/apps/tutorials/local-setup.md
> +If this error is persistent, please create a new directory and initialise a new project in the new location (this location should not be in your cht-core folder).
I'm tempted to say that we should make this a code check in cht-conf, but this change really just adds detail to the above line that's already here. Given that, it seems fine for now.

Slight wording suggestion:
```suggestion
If this error is persistent, please create a new directory and initialise a new project in the new location (outside of your `cht-core` directory tree).
```

I'll approve this now to unblock. If you like your original wording more, it's ok to ignore my suggestion and go with whatever you prefer.

2023-02-10 17:57 UTC, mrjones-plip requested changes
I think this PR is going in the wrong direction.  We already [have explicit code](https://docs.communityhealthtoolkit.org/apps/tutorials/local-setup/#4-create-and-upload-a-blank-project) to create a new directory:

```
mkdir cht-app-tutorials
cd cht-app-tutorials
cht initialise-project-layout
```

It's confusing to add content at the very bottom about creating a new directory which already exists. Instead, I think we should more strongly call out the importance to create the directory in the current instructions .  

Two approaches to this might be:
1. change the `mkdir` call to be `mkdir ~/cht-app-tutorials` and then at the top of every sample code add `cd ~/cht-app-tutorials`. This way when it's copied and pasted folks will always be in the right directory. I did this quite a bit in the [multi-node steps](https://docs.communityhealthtoolkit.org/apps/guides/hosting/4.x/self-hosting-multiple-nodes/#starting-services). While repetitive, it's nice to do to ensure a happy path when something seems possibly overwhelmingly technical to new CHT users.
2. literally add instructions at the top of step 4 that call this out.  Maybe something like: 

   > With `cht-conf` you can also create a blank project. This provides you a template from which you can begin working on CHT. To do so, run the following commands which will create a new directory and initialize it.  Be sure to use this directory for all subsequent calls:

2023-02-10 19:24 UTC, esthermmoturi commented
@Phil-Mwago I think the best approach would be to just add the comment below as @mrjones-plip has suggested.
>> With cht-conf you can also create a blank project. This provides you a template from which you can begin working on CHT. To do so, run the following commands which will create a new directory and initialize it. Be sure to use this directory for all subsequent calls:

2023-02-20 09:34 UTC, esthermmoturi approved these changes
@Phil-Mwago This looks okay. We will keep updating the documentation as need arises.

2023-02-20 13:59 UTC, esthermmoturi approved these changes

2023-02-21 17:18 UTC, mrjones-plip commented on content/en/apps/tutorials/local-setup.md
> +If this error is persistent, please create a new directory and initialise a new project in the new location (this location should not be in your cht-core folder).
This isn't needed now and is still confusing as it feels like a different directory than in step 4. let's remove it:

```suggestion
```

2023-02-21 17:18 UTC, mrjones-plip requested changes
Nice work! I think the updates to step 4 are enough and we should remove the sentence below.

2023-02-23 15:30 UTC, mrjones-plip commented on content/en/apps/tutorials/local-setup.md
> +If this error is persistent, please create a new directory and initialise a new project in the new location (this location should not be in your cht-core folder).
I still think this entire sentence should be removed.

2023-02-23 15:30 UTC, mrjones-plip requested changes
Please remove the sentence I cited in my review.

2023-03-01 15:51 UTC, mrjones-plip approved these changes
per our call - you can remove sentence so I'll approve now - nice work!

@mrjones-plip This is done.

2023-03-02 09:56 UTC, merged